version: "2.7"
services:
  syno-ubuntu:
    image: gpopesc/xfce-ubuntu-synology
    container_name: syno-ubuntu
#    build: .
    environment:
      - VNCPASS=$VNC             #modify .env file 
      - DISPLAY_WIDTH=$WIDTH     #modify .env file 
      - DISPLAY_HEIGHT=$HEIGHT   #modify .env file 
      - TZ=$TZ                   #modify .env file
      - USER_NAME=$USER_NAME      #modify .env file
      - USER_PASSWORD=$USER_PASS  #modify .env file
    ports:
      - $VNCPORT:5900   
      - $HTTPPORT:8000
    volumes:
      - ./data:/home/$USER_NAME   #comment if you run as root, make local foldar "data" next your docker-compose file
      - $LOCAL_PATH:/home/$USER_NAME/share #comment if you run as root # add a server share drive to your home
#      - ./data/root:/root       # uncomment if you run as root, make a local folder  "data/root"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
         size: 4000000000 # ~4gb
    restart: unless-stopped
