version: "3"
services:
  dev-ubu-host:
    image: gpopesc/xfce-ubuntu-xs
    container_name: xfce-ubuntu
#    build: .
    environment:
      - VNCPASS=$VNC               #VNC and root password
      - DISPLAY_WIDTH=$WIDTH
      - DISPLAY_HEIGHT=$HEIGHT
      - TZ=$TZ
      - UID=$UID
      - GID=$GID
      - USER_NAME=$USER_NAME      #comment or delete if you want run as root
      - USER_PASSWORD=$USER_PASS  #comment or delete if you want run as root
    ports:
      - $VNCPORT:5900   
      - $HTTPPORT:8000
    volumes:
      - ./data:/home/$USER_NAME
#      - $LOCAL_PATH:/home/$USER_NAME/share                  # uncomment if want to mount additional share
#      - /run/user/$UID/pulse:/run/user/$UID/pulse:ro        # uncomment in linux if you want sound
      - type: tmpfs
        target: /dev/shm
        tmpfs:
         size: 4000000000 # ~4gb
    restart: on-failure